# Generated by Django 3.1.2 on 2021-09-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iraq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminhod',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
