# Generated by Django 3.1.2 on 2021-09-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iraq', '0002_auto_20210918_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminhod',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
